### ISSUE TITLE
Dark theme: white bar at bottom of window when no folder is opened

### ISSUE THREAD

**Issue by prestonvanloon** [cdonohue/polychrome-vscode-themes#2]
Discussed with you offline about this. The problem as described in the title!

Thanks!

**Comment by cdonohue** [comment]
Thanks for the feedback @prestonvanloon. The goal here was to make it look differently when the window is not associated with a folder/project. At first, it made sense to invert the foreground/background colors.

Maybe an alternative might be to use one of the user specified colors? Like the primary.

So, when a folder/project is opened, the status bar would remain the same as it is today.
>![screen shot 2018-04-05 at 10 05 11 pm](https://user-images.githubusercontent.com/1928846/38401821-aa6497e6-391d-11e8-8918-3c05d29ce7e0.png)

When no folder/project is opened, use the `primary` color
>![screen shot 2018-04-05 at 10 03 40 pm](https://user-images.githubusercontent.com/1928846/38401845-c6e5b670-391d-11e8-98d0-15c215c1b21a.png)

And finally, when the debugger is running, use the `accent` color
>![screen shot 2018-04-05 at 10 04 38 pm](https://user-images.githubusercontent.com/1928846/38401866-df21a65e-391d-11e8-904f-eced9af5db5d.png)

Thoughts?

**Comment by prestonvanloon** [comment]
My main complaint is about the high contrast, but I have no data on which color is best. 

The examples you provided are a nice improvement. Thanks

**Comment by cdonohue** [comment]
Nice! I'll make that change soon then.

**Comment by cdonohue** [comment]
These has been solved with the latest release @prestonvanloon
